export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";
export const SAVE_SETTINGS_START = "SAVE_SETTINGS_START";
export const SAVE_SETTINGS_END = "SAVE_SETTINGS_END";
export const SAVE_SETTINGS_SUCCESS = "SAVE_SETTINGS_SUCCESS";
export const SAVE_SETTINGS_FAILURE = "SAVE_SETTINGS_FAILURE";
export const CLEAR_SAVE_ERROR = "CLEAR_SAVE_ERROR";
