export const GET_BUILDS_SUCCESS = "GET_BUILDS_SUCCESS";
export const GET_BUILDS_FAILURE = "GET_BUILDS_FAILURE";
export const GET_BUILDS_LOADING = "GET_BUILDS_LOADING";
export const RUN_BUILD_SUCCESS = "RUN_BUILD_SUCCESS";
export const RUN_BUILD_FAILURE = "RUN_BUILD_FAILURE";
export const CLEAR_BUILDS = "CLEAR_BUILDS";
