export const GET_BUILD_DETAILS_SUCCESS = "GET_BUILD_DETAILS_SUCCESS";
export const GET_BUILD_DETAILS_FAILURE = "GET_BUILD_DETAILS_FAILURE";
export const GET_BUILD_LOG_SUCCESS = "GET_BUILD_LOG_SUCCESS";
export const GET_BUILD_LOG_FAILURE = "GET_BUILD_LOG_FAILURE";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
