export const GET_BUILD_DETAILS_SUCCESS = "GET_BUILD_DETAILS_SUCCESS";
export const GET_BUILD_DETAILS_FAILURE = "GET_BUILD_DETAILS_FAILURE";
export const GET_BUILD_LOG_SUCCESS = "GET_BUILD_LOG_SUCCESS";
export const GET_BUILD_LOG_FAILURE = "GET_BUILD_LOG_FAILURE";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const LOG_LOADING_START = "LOG_LOADING_START";
export const LOG_LOADING_END = "LOG_LOADING_END";
